name: Notification on push

on:
  release:
    types: [published]
    
jobs:
  sofia:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: LeGitHubDeTai/github-to-discord@main
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Sofia
        DISCORD_AVATAR: https://raw.githubusercontent.com/TaiStudio/Sofia/main/icon.png
        MESSAGE_TITLE: New Version
        MESSAGE_DESCRIPTION: Sofia
        MESSAGE_URL: https://github.com/TaiStudio/Sofia
        MESSAGE_COLOR: 5814783
  taistudio:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: LeGitHubDeTai/github-to-discord@main
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK2 }}
        DISCORD_USERNAME: Tai Studio
        DISCORD_AVATAR: https://raw.githubusercontent.com/TaiStudio/Sofia/main/icon.png
        MESSAGE_TITLE: New Version
        MESSAGE_DESCRIPTION: Sofia
        MESSAGE_URL: https://github.com/TaiStudio/Sofia
        MESSAGE_COLOR: 5814783
